def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TabError(Error_str):
    raise TabError(Error_str)
def r_TimeoutError(Error_str):
    raise TimeoutError(Error_str)
def r_UnicodeTranslateError(Error_str):
    raise UnicodeTranslateError(Error_str)
def r_AttributeError(Error_str):
    raise AttributeError(Error_str)
def r_SystemError(Error_str):
    raise SystemError(Error_str)
# TODO
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
def r_TypeeError(Error_str):
    raise TypeError(Error_str)
